### ISSUE TITLE
If you use double quotes as element locator, element methods in appcontainer-driver.js fails

### ISSUE THREAD

**Issue by kood1** [FINRAOS/MSL#67]
When getting element via locator, if you use double quotes the method fails to return the object since we are not escaping double quotes.  We can either make it a requirement to use single quote or handle double quotes.

**Comment by seoj** [comment]
Mind if I starting taking a look at escaping the quotes?

**Comment by kood1** [comment]
@seoj - please feel free to start working on this and submitting a PR! :-)  Thanks!

**Comment by seoj** [comment]
For the eval() statements, instead of using eval() I was wondering if we could try something like this:

window.frames[0].$('body').append('Appended from parent');

Much safer to use than an eval() and more explicit.
Any thoughts?

**Comment by seoj** [comment]
For now decided to simply escape the quotes. Seems like the suggestion may be more impacting.
